name: "Tag on Pull Request merge"
on:
  # Should trigger only when a Pull Request is Closed
  # (the action will not create the Tag if the Pull Request is discarded - closed without merge)
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  TagOnPR:
    name: Tag on Pull Request merge
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Action
        id: action
        uses: David-Lor/action-tag-on-pr-merge@main
      - name: Print fetched tag
        run: echo "${{ steps.action.outputs.tag }}"
