name: "Tag on Pull Request merge"
on:
  workflow_dispatch: {}
  # Should trigger only when a Pull Request is Closed
  # (the action will not create the Tag if the Pull Request is discarded - closed without merge)
  pull_request:
    types:
      - closed
# TODO uncomment on public repo:
#    branches:
#      - main

jobs:
  TagOnPR:
    name: Tag on Pull Request merge
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get current directory
        run: echo "CWD=$(pwd)" >> $GITHUB_ENV
      - name: Run Action
        id: action
        uses: ${{ env.CWD }}
        with:
          github-token: ${{ secrets.PAT }}  # TODO use GITHUB_TOKEN on public repo
      - name: Print fetched tag
        run: echo "${{ steps.action.outputs.tag }}"
